(() => {
  'use strict';
  const q = s => document.querySelector(s), qa = s => [...document.querySelectorAll(s)];
  const cv = q('#gameCanvas'), x = cv.getContext('2d'), W = cv.width, H = cv.height, CX = W/2, CY = H/2;
  const overlay=q('#gameOverlay'), msg=q('#message');
  const ui={hp:q('#hpValue'),bio:q('#biomassValue'),seed:q('#seedValue'),army:q('#armyValue'),combo:q('#comboValue'),wave:q('#waveValue'),
    cs:q('#collectStatus'),ps:q('#processStatus'),hs:q('#hatchStatus'),es:q('#expandStatus'),cv:q('#collectValue'),pv:q('#processValue'),hv:q('#hatchValue'),ev:q('#expandValue'),od:q('#overdriveBadge'),burst:q('#burstButton')};
  const C={bg:'#121b18',card:'#1a2823',grid:'#31423b',text:'#eef7f2',muted:'#9eb0a7',g:'#63c77f',gd:'#2d5e3c',y:'#e1bc5e',r:'#df756c',b:'#76acd8',p:'#b68bd7',o:'#d98d56'};
  const slots=[[245,148],[325,95],[430,95],[515,148],[535,245],[468,325],[380,355],[292,325],[225,245],[272,238],[488,238],[380,138]];
  let last=performance.now();
  const S={run:false,phase:'intro',doc:'swarm',wave:1,waveT:0,hp:180,maxHp:180,bio:0,seed:0,combo:0,comboT:0,over:0,overT:0,burstT:0,expand:0,goal:15,spawnT:0,flash:0,shake:0,mods:[],minions:[],enemies:[],shots:[],drops:[],drones:[],fx:[],texts:[],stats:{},up:{}};
  const colors=t=>({collector:C.b,processor:C.g,hatchery:C.y,turret:C.p})[t], labels=t=>({collector:'收',processor:'育',hatchery:'孵',turret:'射'})[t];
  const count=t=>S.mods.filter(m=>m.t===t).length;
  function mod(t,s){return{id:Math.random().toString(36).slice(2),t,s,x:slots[s][0],y:slots[s][1],cd:0,work:false,flash:0}}
  function pet(a=Math.random()*Math.PI*2){return{a,cd:Math.random()*.5,x:CX,y:CY}}
  function reset(){Object.assign(S,{run:true,phase:'fight',doc:'swarm',wave:1,waveT:0,hp:180,maxHp:180,bio:0,seed:0,combo:0,comboT:0,over:0,overT:0,burstT:0,expand:0,goal:15,spawnT:.2,flash:0,shake:0,
    mods:[mod('collector',0),mod('processor',2),mod('hatchery',5),mod('turret',7)],minions:[pet(0),pet(Math.PI)],enemies:[],shots:[],drops:[],drones:[],fx:[],texts:[],
    stats:{kills:0,collected:0,processed:0,hatched:2,expanded:0},up:{prod:1,drone:1,turretD:5,turretR:1,petD:2.6,petR:1,petCap:20,boom:.12,boomD:6,over:1}});
    overlay.classList.add('hidden'); chooseDoc('swarm'); msg.textContent='生态循环已启动：击杀、回收、加工、孵化和扩建都会自动完成。';}
  function chooseDoc(v){S.doc=v;qa('[data-doctrine]').forEach(b=>b.classList.toggle('selected',b.dataset.doctrine===v));}
  function nearest(arr,px,py,range=1e9){let r=null,d=range;for(const a of arr){const n=Math.hypot(a.x-px,a.y-py);if(n<d){d=n;r=a}}return r}
  function spawn(){const side=Math.floor(Math.random()*4);let px=side===0?-15:side===1?W+15:Math.random()*W,py=side===2?-15:side===3?H+15:Math.random()*H;const elite=S.wave>=3&&Math.random()<.055,hp=elite?18+S.wave*4:2.2+S.wave;S.enemies.push({x:px,y:py,r:elite?15:9,hp,max:hp,speed:elite?30:39+Math.random()*16,elite,atk:0})}
  function fire(px,py,target,dmg,src,spread=0){const a=Math.atan2(target.y-py,target.x-px)+spread;S.shots.push({x:px,y:py,vx:Math.cos(a)*450,vy:Math.sin(a)*450,d:dmg,src,r:src==='turret'?5:3,life:1.5})}
  function fx(px,py,n=10,p=1){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,v=(25+Math.random()*95)*p;S.fx.push({x:px,y:py,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:.35+Math.random()*.5,s:1.5+Math.random()*2.5})}}
  function text(px,py,v,big=false){S.texts.push({x:px,y:py,v,big,life:1})}
  function area(px,py,r,d){let hits=0;for(let i=S.enemies.length-1;i>=0;i--){const e=S.enemies[i];if(Math.hypot(e.x-px,e.y-py)<=r){e.hp-=d;hits++;if(e.hp<=0)kill(i,true)}}return hits}
  function kill(i,chain=false){const e=S.enemies[i];if(!e)return;S.enemies.splice(i,1);S.drops.push({id:Math.random().toString(36),x:e.x,y:e.y,n:e.elite?5:Math.random()<.35?2:1,taken:false});S.stats.kills++;S.combo=S.comboT>0?S.combo+1:1;S.comboT=1.4;S.over=Math.min(100,S.over+(e.elite?16:3.5)*S.up.over);S.shake=Math.max(S.shake,e.elite?6:2);fx(e.x,e.y,e.elite?22:9,e.elite?1.3:1);if(!chain&&(Math.random()<S.up.boom||S.combo%12===0)){fx(e.x,e.y,18,1.3);area(e.x,e.y,58,S.up.boomD);text(e.x,e.y-15,'连锁爆破',true)}if(S.over>=100&&S.overT<=0){S.over=0;S.overT=7;S.flash=.3;S.shake=8;text(CX,CY-120,'生态超载',true)}}
  function move(a,tx,ty,s,dt){const dx=tx-a.x,dy=ty-a.y,d=Math.max(.001,Math.hypot(dx,dy)),k=Math.min(d,s*dt);a.x+=dx/d*k;a.y+=dy/d*k}
  function drones(dt,mult){const cols=S.mods.filter(m=>m.t==='collector');S.drones=S.drones.filter(d=>cols.some(m=>m.id===d.home));for(const c of cols)if(!S.drones.some(d=>d.home===c.id))S.drones.push({home:c.id,x:c.x,y:c.y,mode:'idle',target:null,cargo:0});cols.forEach(m=>m.work=false);
    for(const d of S.drones){const home=cols.find(m=>m.id===d.home);if(!home)continue;if(d.mode==='idle'){const t=S.drops.filter(v=>!v.taken).sort((a,b)=>Math.hypot(a.x-d.x,a.y-d.y)-Math.hypot(b.x-d.x,b.y-d.y))[0];if(t){t.taken=true;d.target=t.id;d.mode='go'}}if(d.mode==='go'){const t=S.drops.find(v=>v.id===d.target);if(!t){d.mode='idle';continue}home.work=true;move(d,t.x,t.y,180*S.up.drone*mult,dt);if(Math.hypot(d.x-t.x,d.y-t.y)<7){d.cargo=t.n;S.drops.splice(S.drops.indexOf(t),1);d.mode='back'}}if(d.mode==='back'){home.work=true;move(d,home.x,home.y,210*S.up.drone*mult,dt);if(Math.hypot(d.x-home.x,d.y-home.y)<8){S.bio+=d.cargo;S.stats.collected+=d.cargo;S.expand+=d.cargo*.55;text(home.x,home.y-18,`+${d.cargo}`);d.cargo=0;d.mode='idle';d.target=null}}}}
  function modules(dt,mult){for(const m of S.mods){m.cd-=dt*mult;m.flash=Math.max(0,m.flash-dt);m.work=false;if(m.t==='processor'&&S.bio>=2&&m.cd<=0){S.bio-=2;S.seed+=S.up.prod;S.stats.processed+=S.up.prod;S.expand+=1.5*S.up.prod;m.cd=.9;m.flash=.25;m.work=true}if(m.t==='hatchery'&&S.seed>=2&&S.minions.length<S.up.petCap&&m.cd<=0){S.seed-=2;S.minions.push(pet());S.stats.hatched++;S.expand+=2.5;m.cd=1.35;m.flash=.3;m.work=true;fx(m.x,m.y,10)}if(m.t==='turret'){const t=nearest(S.enemies,m.x,m.y,340);m.work=!!t;if(t&&m.cd<=0){fire(m.x,m.y,t,S.up.turretD*(1+Math.min(.6,S.combo*.012)),'turret');if(S.wave>=3){fire(m.x,m.y,t,S.up.turretD*.65,'turret',-.12);fire(m.x,m.y,t,S.up.turretD*.65,'turret',.12)}m.cd=.48/S.up.turretR;m.flash=.16}}}}
  function pets(dt,mult){const n=Math.max(1,S.minions.length);S.minions.forEach((m,i)=>{m.a+=dt*(.55+i%3*.08);const r=62+Math.floor(i/7)*34+i%2*8,a=m.a+i/n*Math.PI*2;m.x=CX+Math.cos(a)*r;m.y=CY+Math.sin(a)*r;m.cd-=dt*mult;const t=nearest(S.enemies,m.x,m.y,280);if(t&&m.cd<=0){fire(m.x,m.y,t,S.up.petD,'pet');m.cd=.75/S.up.petR}})}
  function expand(){if(S.expand<S.goal)return;const used=new Set(S.mods.map(m=>m.s)),slot=slots.findIndex((_,i)=>!used.has(i));if(slot<0){S.expand=0;S.up.prod+=.25;S.up.turretD+=.5;return}let t='processor';if(S.doc==='swarm')t=count('hatchery')<=count('processor')?'hatchery':'processor';if(S.doc==='artillery')t='turret';if(S.doc==='industry')t=count('collector')<=count('processor')?'collector':'processor';const m=mod(t,slot);S.mods.push(m);S.expand-=S.goal;S.goal=Math.min(36,S.goal+3);S.stats.expanded++;S.flash=.2;fx(m.x,m.y,24,1.2);text(m.x,m.y-24,'自动生长',true)}
  function enemies(dt){for(const e of S.enemies){e.atk-=dt;const dx=CX-e.x,dy=CY-e.y,d=Math.max(1,Math.hypot(dx,dy));if(d>39+e.r){e.x+=dx/d*e.speed*dt;e.y+=dy/d*e.speed*dt}else if(e.atk<=0){S.hp-=e.elite?4:1.3;e.atk=e.elite?.9:1.15;S.shake=Math.max(S.shake,2)}}}
  function bullets(dt){for(let i=S.shots.length-1;i>=0;i--){const b=S.shots[i];b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;let hit=false;for(let j=S.enemies.length-1;j>=0;j--){const e=S.enemies[j];if(Math.hypot(e.x-b.x,e.y-b.y)<e.r+b.r){e.hp-=b.d;hit=true;if(e.hp<=0)kill(j);break}}if(hit||b.life<=0||b.x<-20||b.x>W+20||b.y<-20||b.y>H+20)S.shots.splice(i,1)}}
  function burst(){if(S.phase!=='fight'||S.burstT>0)return;S.burstT=7;S.flash=.4;S.shake=11;fx(CX,CY,55,2);const h=area(CX,CY,1000,10+S.wave*2);text(CX,CY-130,`生态爆发 · 命中 ${h}`,true)}
  const upgradePool=()=>[
    ['孢子复制','每次加工额外获得1个种子',()=>S.up.prod++],['蜂群意识','浮游植物攻速提高35%，上限+5',()=>{S.up.petR*=1.35;S.up.petCap+=5}],['高压花冠','炮塔伤害提高40%，射速提高15%',()=>{S.up.turretD*=1.4;S.up.turretR*=1.15}],['连锁尸爆','爆炸概率提高18%',()=>{S.up.boom+=.18;S.up.boomD+=2}],['高速物流','无人机速度提高45%',()=>S.up.drone*=1.45],['永续超载','超载充能加快35%',()=>S.up.over*=1.35],['立即增殖','立刻孵化3个单位',()=>{for(let i=0;i<3;i++)S.minions.push(pet());S.stats.hatched+=3}],['生态装甲','生命上限+50并回满',()=>{S.maxHp+=50;S.hp=S.maxHp}]
  ].sort(()=>Math.random()-.5).slice(0,3);
  function upgrade(){S.phase='upgrade';S.hp=Math.min(S.maxHp,S.hp+35);if(S.wave>=4){finish(true);return}const p=upgradePool();overlay.classList.remove('hidden');overlay.innerHTML=`<div class="overlay-card"><h2>第 ${S.wave} 波完成</h2><p>选择一项强化。</p><div class="upgrade-grid">${p.map((a,i)=>`<button class="upgrade-button" data-u="${i}"><strong>${a[0]}</strong><span>${a[1]}</span></button>`).join('')}</div></div>`;qa('[data-u]',overlay).forEach(b=>b.onclick=()=>{const a=p[+b.dataset.u];a[2]();S.wave++;S.waveT=0;S.phase='fight';S.enemies=[];overlay.classList.add('hidden');text(CX,CY-110,a[0],true)})}
  function finish(win){S.phase=win?'win':'lose';overlay.classList.remove('hidden');overlay.innerHTML=`<div class="overlay-card"><h2>${win?'生态系统完全失控':'生态核心暂时休眠'}</h2><p>击杀 ${S.stats.kills}，回收 ${S.stats.collected}，孵化 ${S.stats.hatched}，自动扩建 ${S.stats.expanded}。</p><button id="again" class="button primary">再次开始</button></div>`;q('#again').onclick=reset}
  function update(dt){if(S.phase==='fight'){S.waveT+=dt;S.spawnT-=dt;S.hp=Math.min(S.maxHp,S.hp+2.1*dt);const gap=Math.max(.12,.48-S.wave*.055-S.waveT*.002);if(S.spawnT<=0){spawn();if(S.wave>=2&&Math.random()<.28)spawn();S.spawnT=gap}const mult=S.overT>0?2.1:1;drones(dt,mult);modules(dt,mult);pets(dt,mult);enemies(dt);bullets(dt);expand();if(S.hp<=0){S.hp=0;finish(false)}else if(S.waveT>=26)upgrade()}S.comboT=Math.max(0,S.comboT-dt);if(!S.comboT)S.combo=0;S.overT=Math.max(0,S.overT-dt);S.burstT=Math.max(0,S.burstT-dt);S.flash=Math.max(0,S.flash-dt);S.shake=Math.max(0,S.shake-dt*15);for(let i=S.fx.length-1;i>=0;i--){const f=S.fx[i];f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.96;f.vy*=.96;f.life-=dt;if(f.life<=0)S.fx.splice(i,1)}for(let i=S.texts.length-1;i>=0;i--){S.texts[i].y-=24*dt;S.texts[i].life-=dt;if(S.texts[i].life<=0)S.texts.splice(i,1)}uiUpdate()}
  function draw(){x.clearRect(0,0,W,H);x.fillStyle=C.bg;x.fillRect(0,0,W,H);x.save();if(S.shake)x.translate((Math.random()-.5)*S.shake,(Math.random()-.5)*S.shake);x.globalAlpha=.15;x.strokeStyle=C.grid;for(let i=20;i<W;i+=40){x.beginPath();x.moveTo(i,0);x.lineTo(i,H);x.stroke()}for(let i=20;i<H;i+=40){x.beginPath();x.moveTo(0,i);x.lineTo(W,i);x.stroke()}x.globalAlpha=1;x.beginPath();x.arc(CX,CY,34,0,7);x.fillStyle=C.gd;x.fill();x.strokeStyle=C.g;x.lineWidth=4;x.stroke();x.beginPath();x.arc(CX,CY,15+Math.sin(performance.now()/180)*2,0,7);x.fillStyle=C.g;x.fill();x.fillStyle=C.grid;x.fillRect(CX-42,CY+43,84,6);x.fillStyle=S.hp/S.maxHp>.35?C.g:C.r;x.fillRect(CX-42,CY+43,84*S.hp/S.maxHp,6);
    for(const d of S.drops){x.beginPath();x.arc(d.x,d.y,5,0,7);x.fillStyle=C.o;x.fill()}for(const m of S.mods){const c=colors(m.t);x.beginPath();x.arc(m.x,m.y,20+(m.flash?5:0),0,7);x.globalAlpha=m.work?.28:.11;x.fillStyle=c;x.fill();x.globalAlpha=1;x.beginPath();x.arc(m.x,m.y,14,0,7);x.fillStyle=C.card;x.fill();x.strokeStyle=c;x.lineWidth=m.work?4:2;x.stroke();x.fillStyle=C.text;x.font='11px sans-serif';x.textAlign='center';x.textBaseline='middle';x.fillText(labels(m.t),m.x,m.y)}for(const d of S.drones){x.beginPath();x.arc(d.x,d.y,6,0,7);x.fillStyle=d.cargo?C.o:C.b;x.fill()}for(const m of S.minions){x.beginPath();x.arc(m.x,m.y,6,0,7);x.fillStyle=C.y;x.fill()}for(const b of S.shots){x.beginPath();x.arc(b.x,b.y,b.r,0,7);x.fillStyle=b.src==='turret'?C.p:C.y;x.fill()}for(const e of S.enemies){x.beginPath();x.arc(e.x,e.y,e.r,0,7);x.fillStyle=e.elite?C.r:C.o;x.fill()}for(const f of S.fx){x.globalAlpha=Math.max(0,f.life*1.8);x.beginPath();x.arc(f.x,f.y,f.s,0,7);x.fillStyle=C.g;x.fill()}x.globalAlpha=1;for(const t of S.texts){x.globalAlpha=t.life;x.fillStyle=t.big?C.y:C.text;x.font=t.big?'bold 17px sans-serif':'12px sans-serif';x.textAlign='center';x.fillText(t.v,t.x,t.y)}x.restore();x.globalAlpha=1;if(S.flash){x.globalAlpha=Math.min(.28,S.flash);x.fillStyle=C.g;x.fillRect(0,0,W,H);x.globalAlpha=1}x.fillStyle=C.text;x.font='13px sans-serif';x.textAlign='left';x.fillText(`剩余 ${Math.max(0,Math.ceil(26-S.waveT))} 秒`,14,20);x.fillText(`击杀 ${S.stats.kills}`,14,40);x.textAlign='right';x.fillStyle=S.overT?C.y:C.muted;x.fillText(S.overT?`生态超载 ${S.overT.toFixed(1)}s`:`敌群 ${S.enemies.length}`,W-14,20)}
  function uiUpdate(){ui.hp.textContent=Math.ceil(S.hp);ui.bio.textContent=Math.floor(S.bio);ui.seed.textContent=Math.floor(S.seed);ui.army.textContent=S.minions.length+count('turret');ui.combo.textContent=S.combo;ui.wave.textContent=`${S.wave}/4`;ui.cv.textContent=S.stats.collected;ui.pv.textContent=S.stats.processed;ui.hv.textContent=S.stats.hatched;ui.ev.textContent=S.stats.expanded;const active=S.drones.filter(d=>d.mode!=='idle').length;ui.cs.textContent=active?`${active}架无人机正在搬运`:'等待新的掉落物';ui.ps.textContent=S.bio>=2?'培育舱正在加工':'等待生物质';ui.hs.textContent=S.seed>=2?'正在自动孵化':'等待种子';ui.es.textContent=`生产进度 ${Math.floor(S.expand)}/${S.goal}`;ui.od.textContent=S.overT?`生态超载 ${S.overT.toFixed(1)}s`:`超载能量 ${Math.floor(S.over)}%`;ui.burst.disabled=S.phase!=='fight'||S.burstT>0;ui.burst.textContent=S.burstT?`生态爆发 ${S.burstT.toFixed(1)}s`:'空格：生态爆发'}
  function frame(now){const dt=Math.min(.035,(now-last)/1000);last=now;update(dt);draw();requestAnimationFrame(frame)}
  q('#startButton').onclick=reset;q('#restartButton').onclick=reset;ui.burst.onclick=burst;qa('[data-doctrine]').forEach(b=>b.onclick=()=>chooseDoc(b.dataset.doctrine));addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();burst()}});S.stats={kills:0,collected:0,processed:0,hatched:2,expanded:0};S.up={prod:1,drone:1,turretD:5,turretR:1,petD:2.6,petR:1,petCap:20,boom:.12,boomD:6,over:1};S.mods=[mod('collector',0),mod('processor',2),mod('hatchery',5),mod('turret',7)];S.minions=[pet(0),pet(Math.PI)];uiUpdate();draw();requestAnimationFrame(frame);
})();
